### ISSUE TITLE
Convert relative URLs to absolute URL.

### ISSUE THREAD

**Issue by na9da** [TerriaJS/catalog-converter#19]
Now that [new routing changes](https://github.com/TerriaJS/terriajs/pull/4679) have landed, relative URLs in catalog definitions will break. 

* We need to auto-convert relative URLs to absolute ones
* Maybe also accept, `--base-url` param to set base URL to something other `/` (eg: `https://nationalmap.org.au/renewables`)

**Comment by soyarsauce** [comment]
This is easily resolved, relative URLs will continue to work if terriamap/terriajs is configured correctly with the base href 🙂
