### ISSUE TITLE
Support share JSON

### ISSUE THREAD

**Issue by steve9164** [TerriaJS/catalog-converter#2]
Add a function or adapt `convertCatalog` to accept and convert share JSON. We will need to embed this in Terria for any app we re-release on TerriaJS version 8 to support current share links.

**Comment by nf-s** [comment]
I will be posting progression updates in [Model architecture: Share & story migration ](https://github.com/terriajs/terriajs/issues/3654)

**Comment by AnaBelgun** [comment]
almost done
Action: @nf-s need to write tests on catalogue converter side
done with stories as well
