### ISSUE TITLE
randomly generate IDs

### ISSUE THREAD

**Issue by nf-s** [TerriaJS/catalog-converter#25]

**Comment by steve9164** [comment]
We should generate IDs for any items & groups that don't already have an ID. This should be a random string of characters, ideally URL compatible characters long enough that the possibility of collisions is low. There should be an option to disable id generation but I think on by default is a good idea.

**Comment by nf-s** [comment]
Done!
And turned on by default (through cli)

**Comment by nf-s** [comment]
See https://github.com/TerriaJS/catalog-converter/pull/32
