### ISSUE TITLE
Investigate missing warnings and errors for nested configuration

### ISSUE THREAD

**Issue by steve9164** [TerriaJS/catalog-converter#3]
Start with:
- [x] Warnings for unconverted tableStyle properties
- [x] Legends
- [x] Look at other

Also need next steps for people. The CLI could print out URLs for migration guide, v8 docs, our GitHub discussions, etc.

**Comment by steve9164** [comment]
Before releasing this new version we should set the cli script as the "bin" script: https://github.com/TerriaJS/catalog-converter/issues/44

**Comment by wibily** [comment]
estimate: 2

**Comment by na9da** [comment]
- [x] tableStyle - PR #46 
- [x] legends - not applicable because v7 legends are either URL string or array of URL strings.
- [x] I scanned other places where the helper functions are called and I couldn't spot any which does not handle unknown props.
