### ISSUE TITLE
Add a static page that uses catalog converter

### ISSUE THREAD

**Issue by steve9164** [TerriaJS/catalog-converter#5]
The page will allow anyone to use catalogue converter on their own Terria version <=7 catalogues without needing to send their catalogue to a server or clone and build the repo.

It should probably be automatically published to a .terria.io domain every time a commit reaches master. We could use AWS Amplify or similar.

We could use Parcel bundler or something like Create React App to make it really simple to make. (Maybe Create React App's service worker setup will be useful here?).

**Comment by soyarsauce** [comment]
This is done now at https://catalog-converter.terria.io/ & https://github.com/TerriaJS/catalog-converter-ui, deployed via netlify
