### ISSUE TITLE
Post-static page work

### ISSUE THREAD

**Issue by soyarsauce** [TerriaJS/catalog-converter#7]
- [x] Add configurable options (mergeRecursive as an example)
- [x] IDs
- [x] mergeRecursive - see comments in https://github.com/TerriaJS/catalog-converter/pull/11

When adding args to yargs, don't add anything with more than 1 dash in it

>Maybe we should add ids to everything as they’re converted

>Run mergeRecursive first

**Comment by soyarsauce** [comment]
Not configurable at all at the moment - can be done at 
https://catalog-converter.terria.io/
master branch of https://github.com/TerriaJS/catalog-converter-ui is auto built

**Comment by AnaBelgun** [comment]
IDs - catalogue converter works better if IDs are clarified 
IDs generation has been changed between v7 and v8
gen rule: if there are no IDs in the catalogue we're converting, we're treating them as in v7
